### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
import numpy as np

array = np.random.randint(1, 51, size=10)

tamanho = 10
#media = (array + array) / tamanho
media = array.mean()

print(array, ":", media)

print("O desvio Padrão é: ", np.std(array)[array =< 0.5])

[11 46 23 18 20 43 10 17 21 44] : 25.3
O desvio Padrão é:  13.054118124178286


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
array = np.random.rand(10)

#array[array <= 0.5] = np.sqrt(array[array <= 0.5])

menor = array[array <= 0.5]
#
raiz = np.sqrt(menor[menor <= 0.5])

print(array, ":", raiz)




[0.70541696 0.81110443 0.87060928 0.70909373 0.02182289 0.61411662
 0.19248042 0.58053654 0.44430776 0.79379013] : [0.14772572 0.4387259  0.66656415]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
matriz = np.random.rand(3, 3, 3)


max_linhas = np.max(matriz, axis= 1)
print(matriz, "\n")
print(max_linhas, "\n")

[[[0.42387311 0.7241669  0.61468522]
  [0.29436302 0.08789099 0.87538206]
  [0.38602795 0.66413833 0.23680283]]

 [[0.22943182 0.05266665 0.86178684]
  [0.00681507 0.69808001 0.25234055]
  [0.8674625  0.68601909 0.74910538]]

 [[0.15350897 0.57392831 0.84812229]
  [0.17032476 0.25594403 0.85667685]
  [0.93422037 0.2446086  0.77923786]]] 

[[0.42387311 0.7241669  0.87538206]
 [0.8674625  0.69808001 0.86178684]
 [0.93422037 0.57392831 0.85667685]] 



### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
matriz = np.random.rand(5, 5)


#media_movel = np.convolve(arr, np.ones(janela) / janela, mode='valid')

media = np.mean(matriz, axis=1)
matriz_linha_media = matriz - media[:, np.newaxis]

print(matriz, "\n")
print(media, "\n")
print(matriz_linha_media, "\n")




#for l in range(len(matrixgg)):
#  m = matrixgg[l].mean()
#  matrixgg[l] -= m
#
# 
#
#print(matrixgg)

[[0.33956683 0.80541921 0.82344563 0.24354454 0.77310474]
 [0.38634296 0.38877021 0.28921443 0.19123287 0.73529172]
 [0.75062182 0.32154097 0.66695186 0.1209469  0.06856841]
 [0.29373402 0.72772843 0.62423946 0.33836505 0.21925191]
 [0.31691837 0.1031799  0.54738611 0.41421055 0.82423369]] 

[0.59701619 0.39817044 0.38572599 0.44066377 0.44118572] 

[[-0.25744936  0.20840302  0.22642944 -0.35347165  0.17608856]
 [-0.01182748 -0.00940023 -0.10895601 -0.20693756  0.33712128]
 [ 0.36489582 -0.06418502  0.28122587 -0.26477909 -0.31715758]
 [-0.14692976  0.28706465  0.18357569 -0.10229872 -0.22141186]
 [-0.12426735 -0.33800582  0.10620039 -0.02697518  0.38304796]] 



### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
matriz = np.random.rand(4, 4)

diag_principal = np.diag(matriz)
diag_secundaria = np.diag(np.fliplr(matriz))
media_diag = np.mean([diag_principal, diag_secundaria])
std_media = np.std([diag_principal, diag_secundaria])

print(matriz, "\n")
print(diag_principal, "\n")
print(diag_secundaria, "\n")
print(media_diag, "\n")
print(std_media, "\n")

[[0.65861569 0.89930413 0.22784524 0.05359585]
 [0.36610502 0.45981106 0.9489431  0.59142641]
 [0.45189544 0.83801475 0.74727097 0.34654946]
 [0.58867616 0.38346906 0.17226615 0.31720427]] 

[0.65861569 0.45981106 0.74727097 0.31720427] 

[0.05359585 0.9489431  0.83801475 0.58867616] 

0.576516479781186 

0.27327576041324364 

